development:
  adapter: postgresql
  database: rails_pirate_development
  host: localhost
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  database: rails_pirate_test
  host: localhost
  pool: 5
  username: root
  password:
